In [4]:
import numpy as np
import pandas as pd


In [62]:
a= [[1,2],[1,3]]##list in python
b=[[5,6],[9,10]]


In [63]:
arr= np.array(a)
brr=np.array(b)## Generating array using numpy

In [64]:
arr
brr

array([[ 5,  6],
       [ 9, 10]])

In [104]:
c= arr.dot(brr)##matrix multiplication i.e Dot product between two matrices
c

array([[23, 26],
       [32, 36]])

In [103]:
d= arr.dot(brr)
d

array([[23, 26],
       [32, 36]])

In [102]:
e=d.dot(c)
e

array([[1361, 1534],
       [1888, 2128]])

In [100]:
f= e.dot(brr)
f

array([[20611, 23506],
       [28592, 32608]])

In [79]:
type(f)  #Shows Datatype of the variable

numpy.ndarray

In [97]:
np.arange(0,9) ##Generates array from given specified value with beginning and end, excluding the end value (Here 0 to 8)

np.arange(0,9,2)  ##Generates array from 0 to 9 with interval of 2   (Start, End, Interval)

array([0, 2, 4, 6, 8])

In [98]:
np.zeros((3,4)) ##used for zero padding in convolutional neural networks

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [99]:
np.linspace(0,10,5)  ##Generates 5 equally spaced values from 0 to 10   (start, end, number of values)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [126]:
np.random.randint(0,10)

## Generates a random integer from a range specified **END VALUE IS NOT INCLUDED SINCE IT'S AN ARRAY

9

In [127]:
np.random.randint(0,11,(3,4))  ## You can also specify the shape of the array 

array([[ 8,  6,  9, 10],
       [ 2,  3,  7,  4],
       [ 3,  7,  3,  3]])

In [134]:
## Random generates random value in every execution. To generate same random value every time, we use seed.
np.random.seed(10)
np.random.randint(2,6)

3

In [182]:
np.random.randn(1,2,3) ## Creates a random value of given dimension (number or arrays, total number of rows, number of column)

array([[[-0.4028531 ,  0.89646319,  0.6556329 ],
        [ 0.56653594,  0.02099563,  0.9142511 ]]])

In [154]:
abc_arr= np.arange(0,10)   ## Has dimension 1 * 1
abc_arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [183]:
abc_arr.reshape(2,5)   
## To change the dimension of given array to specified dimension, used to change the dimension of very lasrge dataset

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
 FURTHER STUDY : https://www.geeksforgeeks.org/numpy-random-randn-python/